csolarproject/csolarapp/urls.py
from . import views
from django.urls import path



    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('detail/',views.detail,name='detail'),
    path('thanks/',views.thanks,name='thanks')
# ]
app_name='csolarapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_solar,name='add_solar'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

csolarproject/csolarproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import csolarapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('csolarapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csolarproject/csolarapp/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Solar(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

csolarproject/csolarapp/forms.py
from django import forms
from .models import Solar

class SolarForm(forms.ModelForm):
    class Meta:
        model=Solar
        fields=['name','desc','year','img']

csolarproject/csolarapp/views.py
# from django.http import HttpResponse
# from django.shortcuts import render
#
#
# # Create your views here.
# def home(request):
#     return HttpResponse("hello")
#
#
# def about(request):
#     name="india"
#     return render(request, "about.html",{'obj':name})
#
#
# def contact(request):
#     return HttpResponse("contact")
#
# def detail(request):
#     return render(request,'detail.html')
# def thanks(request):
#     return HttpResponse("THANK YOU")
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from csolarapp.models import Solar
from .forms import SolarForm

def index(request):
    solar=Solar.objects.all()
    context={
        'solar_list':solar
    }
    return render(request,"index.html",context)
def detail(request, solar_id):
    solar=Solar.objects.get(id=solar_id)
    return render(request,"detail.html",{'solar':solar})
def add_solar(request):

    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        solar=Solar(name=name,desc=desc,year=year,img=img)
        solar.save()

    return render(request,"add.html")
def update(request,id):
    solar=Solar.objects.get(id=id)
    form=SolarForm(request.POST or None, request.FILES,instance=solar)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render (request,'edit.html',{'form':form,'solar':solar})
def delete(request,id):
    if request.method=='POST':
        solar=Solar.objects.get(id=id)
        solar.delete()
        return redirect('/')
    return render(request,'delete.html')

csolarproject/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hai inmakes {{obj}}</h1>
</body>
</html>

csolarproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?

    <input type="submit">
</form>

csolarproject/templates/detail.html
<!--{% extends 'base.html' %}-->
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
         <img src="{{movie.img.url}}" width="200" height="300">
        </div>
<div class="col-md-6">
   <h2> {{solar.name}}</h2>
    <h6>{{solar.desc}}</h6>
    <h6>{{solar.year}}</h6>
    <a class="btn btn-warning" href="{% url 'csolarapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'csolarapp:delete' movie.id %}">delete</a>
    </div>
        </div>
</div>

{% endblock %}

csolarproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">0
</form>

csolarproject/templates/index.html
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-2">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" ><img src="{{i.img.url}}" alt="Card image cap" width=200px" height="300px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'csolarapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>


{% endblock %}